name: AudioLib
description: A library for managing audio channels and playback
version: 2.2.0
homepage: https://github.com/FarragoFiction/AudioLib
author: paradoxLands

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  CommonLib:
    git: git://github.com/FarragoFiction/CommonLib.git
  LoaderLib:
    git: git://github.com/FarragoFiction/LoaderLib.git

dev_dependencies:
  test: ^1.0.0
  build_runner: ^1.0.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0